// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.colors {
    exports com.mastfrog.colors;
    requires java.desktop;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
