// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.swing.miscellaneous {
    exports com.mastfrog.swing;
    exports com.mastfrog.swing.activity;
    exports com.mastfrog.swing.cell;
    exports com.mastfrog.swing.cursor;
    exports com.mastfrog.swing.label;
    exports com.mastfrog.swing.layout;
    exports com.mastfrog.swing.slider;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Sibling com.mastfrog/geometry-3.0.0-dev
    requires com.mastfrog.geometry;
    requires java.desktop;

}
