open module com.mastfrog.swing.miscellaneous {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.swing;
    exports com.mastfrog.swing.activity;
    exports com.mastfrog.swing.cell;
    exports com.mastfrog.swing.cursor;
    exports com.mastfrog.swing.label;
    exports com.mastfrog.swing.layout;
    exports com.mastfrog.swing.slider;
    requires transitive com.mastfrog.geometry;
    requires java.desktop;

}
