open module com.mastfrog.geometry {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.geometry;
    exports com.mastfrog.geometry.analysis;
    exports com.mastfrog.geometry.path;
    exports com.mastfrog.geometry.uirect;
    exports com.mastfrog.geometry.util;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.collections;
    requires java.desktop;
    requires java.logging;

}
