// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.geometry {
    exports com.mastfrog.geometry;
    exports com.mastfrog.geometry.analysis;
    exports com.mastfrog.geometry.path;
    exports com.mastfrog.geometry.uirect;
    exports com.mastfrog.geometry.util;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Transitive detected by source scan
    requires com.mastfrog.search;

    // Inferred from source scan
    requires com.mastfrog.strings;
    requires java.desktop;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
